spring:
  profiles:
    active: DEV

server:
  port: 10001


# 开发环境

---

spring:
  profiles: DEV
  redis:
    host: localhost
    password:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    virtual-host: /push
    # 开启发送失败退回
    publisher-returns: true
    #    设置消息确认类型
    publisher-confirm-type: correlated
    listener:
      direct:
        # 开启ACK
        acknowledge-mode: manual
        prefetch: 1
      simple:
        # 开启ACK
        acknowledge-mode: manual
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/push?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      # 是否允许暂停连接池，暂停后getConnection方法都会被阻塞，用于模拟连接故障，生产环境使用默认配置false
      allow-pool-suspension: false
      #      空闲连接数
      minimum-idle: 5
      #      最大连接数
      maximum-pool-size: 50
      connection-test-query: select 1
#      一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 100000
#      一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 120000
      connection-timeout: 30000
      connection-init-sql: set names utf8mb4
      pool-name: DatebookHikariCP
    driver-class-name: com.mysql.jdbc.Driver

user:
  active: ${spring.profiles.active}
  wsPort: 10002
  ignoreUrl:
    - /access/token